name: CI

on:
  push:
    branches: ['master']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python: ["3.11", "3.12", "3.13", "3.14", "3.15"]

    name: "Python ${{ matrix.python }} / ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v7
        with:
          python-version:: ${{ matrix.python }}

      - run: pip install pytest-mpl

      - run: python -c "import matplotlib"
